FROM rust:1-bullseye

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      musl-tools \
      make \
      gcc \
      ca-certificates && \
    rm -rf /var/lib/apt/lists/*

ENV MUSL_TARGET=x86_64-unknown-linux-musl

RUN rustup target add "${MUSL_TARGET}"

WORKDIR /workspace

CMD ["make", "build"]

